services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: acrbookapp.azurecr.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${AZURE_SQL_CONNECTION_STRING}
    env_file:
      - .env
    networks:
      - bookapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production  # Use nginx production stage
    image: acrbookapp.azurecr.io/frontend:latest
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - bookapp-network

networks:
  bookapp-network:
    driver: bridge