services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: acrbookapp.azurecr.io/backend:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${AZURE_SQL_CONNECTION_STRING}
    env_file:
      - .env
    networks:
      - bookapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development  # Use development stage for hot reload
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app  # Mount source code for hot reload
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - backend
    networks:
      - bookapp-network

networks:
  bookapp-network:
    driver: bridge