name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Backend tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Run backend tests
        run: |
          dotnet restore BookApi.sln
          dotnet build BookApi.sln
          dotnet test BookApi.sln
      
      # Frontend tests
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm ci
          npm run test -- --run
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login \
            acrbookapp.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin
      
      - name: Build and push images
        run: |
          # Build for AMD64 (Azure requirement)
          docker buildx create --use
          
          # Backend
          docker buildx build \
            --platform linux/amd64 \
            --tag acrbookapp.azurecr.io/backend:latest \
            --push \
            ./backend
          
          # Frontend (with production target)
          docker buildx build \
            --platform linux/amd64 \
            --target production \
            --tag acrbookapp.azurecr.io/frontend:latest \
            --push \
            ./frontend
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Container Apps
        run: |
          # Deploy Backend
          az containerapp update \
            --name book-app-api \
            --resource-group rg-bookapp-prod \
            --image acrbookapp.azurecr.io/backend:latest
          
          # Deploy Frontend
          az containerapp update \
            --name book-app-ui \
            --resource-group rg-bookapp-prod \
            --image acrbookapp.azurecr.io/frontend:latest
      
      - name: Verify Deployment
        run: |
          echo "Backend URL: https://book-app-api.wittydesert-f0d21091.centralus.azurecontainerapps.io/"
          echo "Frontend URL: [your-frontend-url]"
          echo "Deployment complete!"