name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Stable URLs from Terraform outputs
  BACKEND_URL: https://book-app-api.wittydesert-f0d21091.centralus.azurecontainerapps.io
  FRONTEND_URL: https://book-app-ui.wittydesert-f0d21091.centralus.azurecontainerapps.io

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Backend tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Run backend tests (unit tests only)
        run: |
          dotnet restore BookApi.sln
          dotnet build BookApi.sln
          dotnet test BookApi.sln
      
      # Frontend tests
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm ci
          npm run test -- --run
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up build timestamp
        run: echo "BUILD_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login \
            acrbookapp.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin
      
      - name: Build and push images
        run: |
          # Build for AMD64 (Azure requirement)
          docker buildx create --use
          
          # Backend with unique tag
          echo "Building backend image with tag: ${{ env.BUILD_TAG }}"
          docker buildx build \
            --platform linux/amd64 \
            --tag acrbookapp.azurecr.io/backend:${{ env.BUILD_TAG }} \
            --tag acrbookapp.azurecr.io/backend:latest \
            --push \
            ./backend
          
          # Frontend with stable backend URL and unique tag
          echo "Building frontend image with API URL: ${{ env.BACKEND_URL }}/api and tag: ${{ env.BUILD_TAG }}"
          docker buildx build \
            --platform linux/amd64 \
            --target production \
            --build-arg VITE_API_URL=${{ env.BACKEND_URL }}/api \
            --tag acrbookapp.azurecr.io/frontend:${{ env.BUILD_TAG }} \
            --tag acrbookapp.azurecr.io/frontend:latest \
            --push \
            ./frontend
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Container Apps with forced revision
        run: |
          # Deploy Backend with unique image tag and revision suffix
          echo "Deploying backend with tag: ${{ env.BUILD_TAG }}"
          az containerapp update \
            --name book-app-api \
            --resource-group rg-bookapp-prod \
            --image acrbookapp.azurecr.io/backend:${{ env.BUILD_TAG }} \
            --revision-suffix ${{ env.BUILD_TAG }}
          
          # Deploy Frontend with unique image tag and revision suffix
          echo "Deploying frontend with tag: ${{ env.BUILD_TAG }}"
          az containerapp update \
            --name book-app-ui \
            --resource-group rg-bookapp-prod \
            --image acrbookapp.azurecr.io/frontend:${{ env.BUILD_TAG }} \
            --revision-suffix ${{ env.BUILD_TAG }}
      
      - name: Verify Deployment
        run: |
          echo "========================================="
          echo "Deployment Complete!"
          echo "Build Tag: ${{ env.BUILD_TAG }}"
          echo "Backend URL: ${{ env.BACKEND_URL }}"
          echo "Frontend URL: ${{ env.FRONTEND_URL }}"
          echo "========================================="
          
          # List new revisions
          echo "Backend revisions:"
          az containerapp revision list \
            --name book-app-api \
            --resource-group rg-bookapp-prod \
            --query "[0:3].{Name:name, Active:properties.active, Created:properties.createdTime}" \
            -o table
          
          echo "Frontend revisions:"
          az containerapp revision list \
            --name book-app-ui \
            --resource-group rg-bookapp-prod \
            --query "[0:3].{Name:name, Active:properties.active, Created:properties.createdTime}" \
            -o table
          
          # Test endpoints
          echo "Testing backend health..."
          curl -f ${{ env.BACKEND_URL }}/health || echo "Backend health check failed"
          
          echo "Testing frontend..."
          curl -f ${{ env.FRONTEND_URL }} || echo "Frontend check failed"